require:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  SuggestExtensions: false

Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

Layout/LineLength:
  Max: 120

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false
  Exclude:
    - "spec/**/*.rb"

Style/Documentation:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/BeforeAfterAll:
  Enabled: false
